### ISSUE TITLE
Please remove useless files from repo

### ISSUE THREAD

**Issue by pcav** [vasuda23/SaTSviz_2#1]
.pyc, .gitignore, and the like.

**Comment by pcav** [comment]
also pycache

**Comment by pcav** [comment]
Sorry, I still see ti. Please remove them also from the package, and upload a new version.

**Comment by vasuda23** [comment]
I have to remove it from where.

**Comment by pcav** [comment]
Both from github and from the zipfile

**Comment by pcav** [comment]
Please do not close an issue before fixing it.

**Comment by vasuda23** [comment]
i have deleted the payload file. rest which file i have to delete

**Comment by pcav** [comment]
As said, all compiled files (*.pyc) and the __pycache__ dir

**Comment by vasuda23** [comment]
ok got it. Just uploading.

**Comment by vasuda23** [comment]
Please check now.

**Comment by vasuda23** [comment]
Is it fine or not.

**Comment by vasuda23** [comment]
Thank you so much sir
